import {Specimen} from './specimen';

export const DEMO_INVENTORY_NAME: string = 'demoInventory';

export const DEMO_INVENTORY_SPECIMENS: Specimen[] = [
  {
    id: 0,
    selected: true,
    number: 'LTG-001',
    phylum: 'Mollusca',
    class: 'Cephalopoda',
    order: 'Ammonitida',
    family: '',
    genus: "Hildoceras",
    species: 'bifrons',
    author: '(Bruguière, 1789)',
    age: 'Toarcian',
    lithostratigraphy: 'Calcaire',
    country: "France",
    region: "Bourgogne",
    location: "Pouillenay"
  },

  {
    id: 1,
    selected: true,
    number: 'LTG-002',
    phylum: 'Cnidaria',
    class: 'Anthozoa',
    order: 'Scleractinia',
    family: 'Actinastreidae',
    genus: 'Chondrocoenia',
    species: 'clavellata',
    author: 'Terquem and Piette, 1865',
    age: 'Sinemurian',
    lithostratigraphy: 'Calcaire',
    country: 'Morocco',
    region: "Haut Atlas",
    location: 'Amellagou'
  },
  {
    id: 2,
    selected: true,
    number: 'LTG-003',
    phylum: 'Cnidaria',
    class: 'Anthozoa',
    order: 'Hexanthiniaria ?',
    family: 'Hispaniastraeidae',
    genus: 'Hispaniastraea',
    species: 'muricana',
    author: 'Turnsek and Geyer, 1975',
    age: 'Sinemurian',
    lithostratigraphy: 'Calcaire',
    country: 'Morocco',
    region: "Haut Atlas",
    location: 'Amellagou'
  },
  {
    id: 3,
    selected: true,
    number: 'LTG-004',
    phylum: 'Cnidaria',
    class: 'Anthozoa',
    order: 'Scleractinia',
    family: 'Coryphylliidae',
    genus: 'Coryphyllia',
    species: 'regularis',
    author: 'Cuif, 1975',
    age: 'Pliensbachian',
    lithostratigraphy: 'Calcaire',
    country: 'Morocco',
    region: "Haut Atlas",
    location: 'Amellagou'
  },
  {
    id: 4,
    selected: true,
    number: 'LTG-005',
    phylum: 'Cnidaria',
    class: 'Anthozoa',
    order: 'Hexanthiniaria ?',
    family: 'Hispaniastraeidae',
    genus: 'Hispaniastraea',
    species: 'muricana',
    author: 'Turnsek and Geyer, 1975',
    age: 'Sinemurian',
    lithostratigraphy: 'Calcaire',
    country: 'Morocco',
    region: "Haut Atlas",
    location: 'Amellagou'
  },
  {
    id: 5,
    selected: true,
    number: 'LTG-006',
    phylum: 'Cnidaria',
    class: 'Anthozoa',
    order: 'Scleractinia',
    family: 'Stylophyllidae',
    genus: 'Phacelostylophyllum',
    species: 'suttonensis',
    author: '(Duncan, 1867)',
    age: 'Sinemurian',
    lithostratigraphy: 'Calcaire',
    country: 'Morocco',
    region: "Haut Atlas",
    location: 'Amellagou'
  },
  {
    id: 6,
    selected: true,
    number: 'LTG-007',
    phylum: 'Cnidaria',
    class: 'Anthozoa',
    order: 'Scleractinia',
    family: 'Stylophyllidae',
    genus: 'Phacelostylophyllum',
    species: 'martini',
    author: '(Fromentel, 1860)',
    age: 'Sinemurian',
    lithostratigraphy: 'Calcaire',
    country: 'Morocco',
    region: "Haut Atlas",
    location: 'Amellagou'
  },
  {
    id: 7,
    selected: true,
    number: 'LTG-008',
    phylum: 'Cnidaria',
    class: 'Anthozoa',
    order: 'Scleractinia',
    family: 'Incertae sedis',
    genus: 'Vallimeandropsis',
    species: 'lineata',
    author: '(Beauvais, 1986)',
    age: 'Sinemurian / Pliensbachian',
    lithostratigraphy: 'Calcaire',
    country: 'Morocco',
    region: "Haut Atlas",
    location: 'Amellagou'
  },
  {
    id: 8,
    selected: true,
    number: 'LTG-009',
    phylum: 'Cnidaria',
    class: 'Anthozoa',
    order: 'Scleractinia',
    family: 'Coryphylliidae',
    genus: 'Coryphyllia',
    species: 'regularis',
    author: 'Cuif, 1975',
    age: 'Sinemurian / Pliensbachian',
    lithostratigraphy: 'Calcaire',
    country: 'Morocco',
    region: "Haut Atlas",
    location: 'Amellagou'
  },
  {
    id: 9,
    selected: true,
    number: 'LTG-010',
    phylum: 'Cnidaria',
    class: 'Anthozoa',
    order: 'Scleractinia',
    family: 'Dermosmiliidae',
    genus: 'Proleptophyllia',
    species: 'granulum',
    author: '(Fromentel & Ferry, 1866)',
    age: 'Pliensbachian',
    lithostratigraphy: 'Calcaire',
    country: 'Morocco',
    region: "Haut Atlas",
    location: 'Amellagou'
  },
  {
    id: 10,
    selected: true,
    number: 'LTG-011',
    phylum: 'Cnidaria',
    class: 'Anthozoa',
    order: 'Scleractinia',
    family: 'Stylophyllidae',
    genus: 'Chondrocoenia',
    species: 'plana',
    author: '(Duncan, 1867)',
    age: 'Pliensbachian',
    lithostratigraphy: 'Calcaire',
    country: 'Morocco',
    region: "Haut Atlas",
    location: 'Amellagou'
  },
  {
    id: 11,
    selected: true,
    number: 'LTG-012',
    phylum: 'Cnidaria',
    class: 'Anthozoa',
    order: 'Scleractinia',
    family: 'Astraeomorphidae',
    genus: 'Parastraeomorpha',
    species: 'minuscula',
    author: 'Roniewicz, 1989',
    age: 'Pliensbachian',
    lithostratigraphy: 'Calcaire',
    country: 'Morocco',
    region: "Haut Atlas",
    location: 'Amellagou'
  },
];
